[build]
  publish = "frontend/dist"            # ✅ point to frontend build output
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://real-time-chatty-application.onrender.com/api"  # ✅ available to Vite during build

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev --prefix frontend"
  port = 5173
  publish = "frontend/dist"
